name: myapp
services:
  mariadb-gian:
    build:
      context: .
      dockerfile: mariadb.Containerfile
    container_name: mariadb-gian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: db_akademik
      MYSQL_USER: gian
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  php-apache-gian:
    build:
      context: .
      dockerfile: php-apache.Containerfile
    container_name: php-apache-gian
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html:z
    environment:
      DB_HOST: mariadb-gian
      DB_NAME: db_akademik
      DB_USER: gian
      DB_PASS: 123
      DB_PORT: 3306
    depends_on:
      - mariadb-gian

  phpmyadmin-gian:
    image: docker.io/phpmyadmin/phpmyadmin
    container_name: phpmyadmin-gian
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mariadb-gian
      PMA_PORT: 3306
    depends_on:
      - mariadb-gian

volumes:
  mariadb_data: